# Generated by Django 6.0.2 on 2026-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumbnail_url_lecture_lecture_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='resources_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
